-- Auto-generated by matugen. Do not edit manually.
local M = {}
M.colors = {
  primary            = "#91d6a2",
  on_primary         = "#00391b",
  primary_container  = "#3f8154",
  secondary          = "#b1ceb5",
  on_secondary       = "#1e3624",
  surface            = "#111411",
  on_surface         = "#e0e3dd",
  surface_variant    = "#404941",
  on_surface_variant = "#c0c9be",
  background         = "#111411",
  on_background      = "#e0e3dd",
  error              = "#ffb4ab",
  on_error           = "#690005",
  outline            = "#8a9389",
  outline_variant    = "#404941",
  tertiary           = "#9fcaff",
  on_tertiary        = "#003258",
}
return M
