-- Auto-generated by matugen. Do not edit manually.
local M = {}
M.colors = {
  primary            = "#cabeff",
  on_primary         = "#31009a",
  primary_container  = "#5c38dd",
  secondary          = "#cabeff",
  on_secondary       = "#31256a",
  surface            = "#14121b",
  on_surface         = "#e6e0ee",
  surface_variant    = "#484555",
  on_surface_variant = "#c9c4d8",
  background         = "#14121b",
  on_background      = "#e6e0ee",
  error              = "#ffb4ab",
  on_error           = "#690005",
  outline            = "#938ea1",
  outline_variant    = "#484555",
  tertiary           = "#ffabef",
  on_tertiary        = "#5c0058",
}
return M
