-- Auto-generated by matugen. Do not edit manually.
local M = {}
M.colors = {
  primary            = "{{colors.primary.default.hex}}",
  on_primary         = "{{colors.on_primary.default.hex}}",
  primary_container  = "{{colors.primary_container.default.hex}}",
  secondary          = "{{colors.secondary.default.hex}}",
  on_secondary       = "{{colors.on_secondary.default.hex}}",
  surface            = "{{colors.surface.default.hex}}",
  on_surface         = "{{colors.on_surface.default.hex}}",
  surface_variant    = "{{colors.surface_variant.default.hex}}",
  on_surface_variant = "{{colors.on_surface_variant.default.hex}}",
  background         = "{{colors.background.default.hex}}",
  on_background      = "{{colors.on_background.default.hex}}",
  error              = "{{colors.error.default.hex}}",
  on_error           = "{{colors.on_error.default.hex}}",
  outline            = "{{colors.outline.default.hex}}",
  outline_variant    = "{{colors.outline_variant.default.hex}}",
  tertiary           = "{{colors.tertiary.default.hex}}",
  on_tertiary        = "{{colors.on_tertiary.default.hex}}",
}
return M
